spring:
  application:
    name: video_backend
  datasource:
    url: jdbc:mysql://localhost:3306/videos?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  media:
    base-path: C:\Users\isaac\Documents\proyecto videos\video_backend\media


